cvm-version: 0.11.0
cpus: 8
memory: 16384

containers:
  - name: "summarizer"
    image: "ghcr.io/tinfoilsh/confidential-summarizer@sha256:3c4fe3b2e423094aa0a7c337b7e1671b2f627ac162149a2fad40f76ede9042bf" # v0.1.15
    restart: always
    networks: [web]
    env:
      - SUMMARY_MODEL: "llama3-3-70b"
    secrets:
      - TINFOIL_API_KEY

networks:
  web:
    egress: open

shim:
  upstream-port: 8089
  paths:
    - /summarize
    - /health
